<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>AccessManagement.Application.UnitTests</RootNamespace>
        <AssemblyName>AccessManagement.Application.UnitTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="nunit" />
        <PackageReference Include="NUnit.Analyzers">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Moq" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Core\AccessManagement.Application\AccessManagement.Application.csproj" />
        <ProjectReference Include="..\..\src\Core\AccessManagement.Domain\AccessManagement.Domain.csproj" />
        <ProjectReference Include="..\..\src\Core\AccessManagement.Infrastructure\AccessManagement.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\TestSupport\TestGuids.cs" Link="TestSupport\TestGuids.cs" />
        <Compile Include="..\TestSupport\TestPasswords.cs" Link="TestSupport\TestPasswords.cs" />
    </ItemGroup>

</Project>
