<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Qc.AccessPlugin.Tests</RootNamespace>
    <AssemblyName>Qc.AccessPlugin.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="nunit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Qc.AccessPlugin\Qc.AccessPlugin.csproj" />
    <ProjectReference Include="..\..\src\Core\AccessManagement.Application\AccessManagement.Application.csproj" />
    <ProjectReference Include="..\..\src\Core\AccessManagement.Domain\AccessManagement.Domain.csproj" />
    <ProjectReference Include="..\..\src\Core\AccessManagement.Infrastructure\AccessManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
